# Detect T2 MacBook models using PCI IDs
# Vendor: 106b (Apple), Device IDs: 1801 or 1802 (T2 Security Chip)
if lspci -nn | grep "106b:180[12]" >/dev/null; then
  echo "Detected MacBook with T2 chip. Installing support items..."

  # linux-t2, apple-t2-audio-config, apple-bcm-firmware, and t2fanrd have no
  # Fedora RPMs. T2 support on Fedora is a community effort (t2linux); check
  # for a current Fedora COPR before reviving kernel/audio/fan packages.
  # The module loading, boot args, and firmware config below still apply to a
  # T2-patched kernel.
  echo "T2 Mac detected: install a T2-patched kernel plus t2fanrd from the community before relying on this hardware." >&2

  mkdir -p /etc/modules-load.d
  {
    echo "t2bce_vhci"
    echo "hci_bcm4377"
  } > /etc/modules-load.d/t2.conf

  # t2bce_vhci is the virtual USB host controller the internal keyboard hangs
  # off. Pull it (and its t2bce_core/t2bce_dma dependencies) into the initramfs
  # via dracut; rebuilt by limine-mkinitcpio.
  mkdir -p /etc/dracut.conf.d
  echo 'add_drivers+=" t2bce_vhci usbhid hid_apple hid_generic xhci_pci xhci_hcd "' > \
    /etc/dracut.conf.d/apple-t2.conf

  mkdir -p /etc/limine-entry-tool.d
  cat > /etc/limine-entry-tool.d/t2-mac.conf <<'EOF'
# Generated by Omarchy installer for T2 Mac support
KERNEL_CMDLINE[default]+=" intel_iommu=on iommu=pt pm_async=off mem_sleep_default=deep"
EOF

  # t2fanrd only reads sections for detected fans, so Fan2 is harmless on
  # single-fan models and required on dual-fan MacBooks.
  cat > /etc/t2fand.conf <<'EOF'
[Fan1]
low_temp=55
high_temp=75
speed_curve=linear
always_full_speed=false

[Fan2]
low_temp=55
high_temp=75
speed_curve=linear
always_full_speed=false
EOF
fi
